# Specify the HTCondor Universe (vanilla is the default)
universe = vanilla
#
# Log Out Error 
log = $(genome)_LPOfind.log
error = $(genome)_LPOfind.err
#output = $(genome)_PPOfind.out
#
# Executable and arguments if any
executable = LPOfind.sh
arguments = $(genome) Lipoxygenase
#
requirements = (Target.HasCHTCStaging == true)
#
# Inputs/Outputs
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/groups/keller_group/FungalGenomes/$(genome)/$(genome)_hmmer.out
transfer_output_files = $(genome)_LPO.tsv
#
# Tell HTCondor what amount of compute resources
request_cpus = 1
request_memory = 300MB
request_disk = 300MB
# 
# Increasing the number of files that can be run at one time
## Allows it to also go to HTCondor Pools
+WantFlocking = true
## Allows it to also go to OS Pool
+WantGlideIn = true
#
# Query files, use the testing or full file and comment out the other one
queue genome from /home/hpestes/complete_projects/DanteOxylipin/testlist.txt
#queue genome from /home/hpestes/complete_projects/DanteOxylipin/singlegenome_perspecies.txt